/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package computerhardwarestore;

/**
 *
 * @author fahee
 */
public class brandManufacturer extends javax.swing.JFrame {

    /**
     * Creates new form brandManufacturer
     */
    public brandManufacturer() {
        initComponents();
        jPanel3.hide();
        jLabel10.hide();
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        LogoutSymbol = new javax.swing.JLabel();
        SubmitButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        Products = new javax.swing.JButton();
        Employee = new javax.swing.JButton();
        brandManu = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        shop1 = new javax.swing.JButton();
        Accessories = new javax.swing.JButton();
        Computer = new javax.swing.JButton();
        Components = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        SubmitButton1 = new javax.swing.JButton();
        SubmitButton2 = new javax.swing.JButton();
        SubmitButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(" Manufacture");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, 170, 40));

        jTable2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable2.setFont(new java.awt.Font("Agency FB", 0, 11)); // NOI18N
        jTable2.setForeground(new java.awt.Color(51, 51, 51));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setGridColor(new java.awt.Color(0, 102, 102));
        jTable2.setRowHeight(24);
        jTable2.setSelectionBackground(new java.awt.Color(0, 102, 102));
        jTable2.setShowGrid(true);
        jScrollPane3.setViewportView(jTable2);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 640, 210));

        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setFont(new java.awt.Font("Agency FB", 0, 11)); // NOI18N
        jTable1.setForeground(new java.awt.Color(51, 51, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(0, 102, 102));
        jTable1.setRowHeight(24);
        jTable1.setSelectionBackground(new java.awt.Color(0, 102, 102));
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 640, 210));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Group 8 (1).png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DashBoard");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 300, 10));

        LogoutSymbol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        jPanel4.add(LogoutSymbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 30, 40));

        SubmitButton.setBackground(new java.awt.Color(0, 51, 51));
        SubmitButton.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        SubmitButton.setForeground(new java.awt.Color(255, 255, 255));
        SubmitButton.setText("Log-Out");
        SubmitButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SubmitButton.setContentAreaFilled(false);
        SubmitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitButtonMouseClicked(evt);
            }
        });
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });
        jPanel4.add(SubmitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, 110, 40));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 68, 300, -1));

        Products.setBackground(new java.awt.Color(0, 51, 51));
        Products.setFont(new java.awt.Font("Agency FB", 1, 28)); // NOI18N
        Products.setForeground(new java.awt.Color(255, 255, 255));
        Products.setText("Products");
        Products.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Products.setContentAreaFilled(false);
        Products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductsMouseClicked(evt);
            }
        });
        Products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductsActionPerformed(evt);
            }
        });
        jPanel4.add(Products, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 170, -1));

        Employee.setBackground(new java.awt.Color(0, 51, 51));
        Employee.setFont(new java.awt.Font("Agency FB", 0, 28)); // NOI18N
        Employee.setForeground(new java.awt.Color(255, 255, 255));
        Employee.setText("Employee");
        Employee.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Employee.setContentAreaFilled(false);
        Employee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeeMouseClicked(evt);
            }
        });
        Employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeActionPerformed(evt);
            }
        });
        jPanel4.add(Employee, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 170, -1));

        brandManu.setBackground(new java.awt.Color(0, 51, 51));
        brandManu.setFont(new java.awt.Font("Agency FB", 1, 28)); // NOI18N
        brandManu.setForeground(new java.awt.Color(255, 255, 255));
        brandManu.setText("Manufacturer");
        brandManu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        brandManu.setContentAreaFilled(false);
        brandManu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                brandManuMouseClicked(evt);
            }
        });
        brandManu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandManuActionPerformed(evt);
            }
        });
        jPanel4.add(brandManu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 170, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/up.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/down.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        shop1.setBackground(new java.awt.Color(0, 51, 51));
        shop1.setFont(new java.awt.Font("Agency FB", 0, 28)); // NOI18N
        shop1.setForeground(new java.awt.Color(255, 255, 255));
        shop1.setText("Shop");
        shop1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        shop1.setContentAreaFilled(false);
        shop1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shop1MouseClicked(evt);
            }
        });
        shop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shop1ActionPerformed(evt);
            }
        });
        jPanel4.add(shop1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 170, -1));

        Accessories.setBackground(new java.awt.Color(0, 51, 51));
        Accessories.setFont(new java.awt.Font("Agency FB", 0, 28)); // NOI18N
        Accessories.setForeground(new java.awt.Color(255, 255, 255));
        Accessories.setText("Accessories");
        Accessories.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Accessories.setContentAreaFilled(false);
        Accessories.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccessoriesMouseClicked(evt);
            }
        });
        Accessories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccessoriesActionPerformed(evt);
            }
        });
        jPanel4.add(Accessories, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 170, -1));

        Computer.setBackground(new java.awt.Color(0, 51, 51));
        Computer.setFont(new java.awt.Font("Agency FB", 0, 28)); // NOI18N
        Computer.setForeground(new java.awt.Color(255, 255, 255));
        Computer.setText("Computer");
        Computer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Computer.setContentAreaFilled(false);
        Computer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComputerMouseClicked(evt);
            }
        });
        Computer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComputerActionPerformed(evt);
            }
        });
        jPanel4.add(Computer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 170, -1));

        Components.setBackground(new java.awt.Color(0, 51, 51));
        Components.setFont(new java.awt.Font("Agency FB", 0, 28)); // NOI18N
        Components.setForeground(new java.awt.Color(255, 255, 255));
        Components.setText("Components");
        Components.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Components.setContentAreaFilled(false);
        Components.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComponentsMouseClicked(evt);
            }
        });
        Components.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComponentsActionPerformed(evt);
            }
        });
        jPanel4.add(Components, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 170, -1));

        jScrollPane2.setViewportView(jPanel4);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Brand Manufacture");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, 170, 40));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setText("Name");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 87, 32));

        jComboBox1.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 51, 51));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "option 1", "option 2", "option 3", "option 4", " " }));
        jComboBox1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 90, 22));

        SubmitButton1.setBackground(new java.awt.Color(255, 255, 255));
        SubmitButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SubmitButton1.setForeground(new java.awt.Color(255, 255, 255));
        SubmitButton1.setText("Update");
        SubmitButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SubmitButton1.setContentAreaFilled(false);
        SubmitButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitButton1MouseClicked(evt);
            }
        });
        SubmitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(SubmitButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, -1));

        SubmitButton2.setBackground(new java.awt.Color(255, 255, 255));
        SubmitButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SubmitButton2.setForeground(new java.awt.Color(255, 255, 255));
        SubmitButton2.setText("Add");
        SubmitButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SubmitButton2.setContentAreaFilled(false);
        SubmitButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitButton2MouseClicked(evt);
            }
        });
        SubmitButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(SubmitButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        SubmitButton3.setBackground(new java.awt.Color(255, 255, 255));
        SubmitButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SubmitButton3.setForeground(new java.awt.Color(255, 255, 255));
        SubmitButton3.setText("Delete");
        SubmitButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SubmitButton3.setContentAreaFilled(false);
        SubmitButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitButton3MouseClicked(evt);
            }
        });
        SubmitButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(SubmitButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        jTextField2.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(102, 102, 102));
        jTextField2.setText("jTextField1");
        jTextField2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 215, 28));

        jTextField3.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(102, 102, 102));
        jTextField3.setText("Search");
        jTextField3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 215, 28));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img39one.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 290, 420));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Group 8 (1).png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CHSdb.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1790, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DataBaseBG.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1060));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1101, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        jPanel4.hide();
        jScrollPane2.hide();
        jPanel3.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void SubmitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitButtonMouseClicked
        new signIn().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SubmitButtonMouseClicked

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void ProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductsMouseClicked
        // TODO add your handling code here:
        new managerProduct().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ProductsMouseClicked

    private void ProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductsActionPerformed

    private void EmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeMouseClicked
        // TODO add your handling code here:
        new managerEmployee().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EmployeeMouseClicked

    private void EmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeActionPerformed

    private void brandManuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brandManuMouseClicked
        // TODO add your handling code here:
        new brandManufacturer().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_brandManuMouseClicked

    private void brandManuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandManuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandManuActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        jLabel10.setVisible(true);
        jLabel9.hide();
        Components.hide();
        Computer.hide();
        Accessories.hide();
        brandManu.hide();

    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        jLabel10.hide();
        brandManu.setVisible(true);
        Accessories.setVisible(true);
        jLabel9.setVisible(true);
        Components.setVisible(true);
        Computer .setVisible(true);

    }//GEN-LAST:event_jLabel10MouseClicked

    private void shop1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shop1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_shop1MouseClicked

    private void shop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shop1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shop1ActionPerformed

    private void AccessoriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccessoriesMouseClicked
        // TODO add your handling code here:
        new managerAccessories().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AccessoriesMouseClicked

    private void AccessoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccessoriesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccessoriesActionPerformed

    private void ComputerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComputerMouseClicked
        // TODO add your handling code here:
        new managerComputer().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ComputerMouseClicked

    private void ComputerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComputerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComputerActionPerformed

    private void ComponentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComponentsMouseClicked
        // TODO add your handling code here:
        new managerComponents().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ComponentsMouseClicked

    private void ComponentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComponentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComponentsActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void SubmitButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitButton1MouseClicked

    private void SubmitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButton1ActionPerformed

    }//GEN-LAST:event_SubmitButton1ActionPerformed

    private void SubmitButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitButton2MouseClicked

    private void SubmitButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitButton2ActionPerformed

    private void SubmitButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitButton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitButton3MouseClicked

    private void SubmitButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitButton3ActionPerformed

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        jPanel3.hide();
        jPanel4.setVisible(true);
        jScrollPane2.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        jPanel4.hide();
        jScrollPane2.hide();
        jPanel3.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(brandManufacturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(brandManufacturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(brandManufacturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(brandManufacturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new brandManufacturer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Accessories;
    private javax.swing.JButton Components;
    private javax.swing.JButton Computer;
    private javax.swing.JButton Employee;
    private javax.swing.JLabel LogoutSymbol;
    private javax.swing.JButton Products;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JButton SubmitButton1;
    private javax.swing.JButton SubmitButton2;
    private javax.swing.JButton SubmitButton3;
    private javax.swing.JButton brandManu;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton shop1;
    // End of variables declaration//GEN-END:variables
}
