/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package computerhardwarestore;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author fahee
 */
public class employeeBuy extends javax.swing.JFrame {

    /**
     * Creates new form employeeBuy
     */
    public employeeBuy() {
        initComponents();
        jPanel3.hide();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        LogoutSymbol = new javax.swing.JLabel();
        SubmitButton = new javax.swing.JButton();
        SubmitButton5 = new javax.swing.JButton();
        SubmitButton7 = new javax.swing.JButton();
        SubmitButton12 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        SubmitButton13 = new javax.swing.JButton();
        SubmitButton14 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        SubmitButton1 = new javax.swing.JButton();
        SubmitButton2 = new javax.swing.JButton();
        SubmitButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setFont(new java.awt.Font("Agency FB", 0, 11)); // NOI18N
        jTable1.setForeground(new java.awt.Color(51, 51, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(0, 102, 102));
        jTable1.setRowHeight(24);
        jTable1.setSelectionBackground(new java.awt.Color(0, 102, 102));
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 640, 470));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Group 8 (1).png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DashBoard");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 300, 10));

        LogoutSymbol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        jPanel4.add(LogoutSymbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 30, 40));

        SubmitButton.setBackground(new java.awt.Color(0, 51, 51));
        SubmitButton.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        SubmitButton.setForeground(new java.awt.Color(255, 255, 255));
        SubmitButton.setText("Log-Out");
        SubmitButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SubmitButton.setContentAreaFilled(false);
        SubmitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitButtonMouseClicked(evt);
            }
        });
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });
        jPanel4.add(SubmitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, 110, 40));

        SubmitButton5.setBackground(new java.awt.Color(0, 51, 51));
        SubmitButton5.setFont(new java.awt.Font("Agency FB", 0, 28)); // NOI18N
        SubmitButton5.setForeground(new java.awt.Color(255, 255, 255));
        SubmitButton5.setText("Customer");
        SubmitButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SubmitButton5.setContentAreaFilled(false);
        SubmitButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitButton5MouseClicked(evt);
            }
        });
        SubmitButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(SubmitButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 170, -1));

        SubmitButton7.setBackground(new java.awt.Color(0, 51, 51));
        SubmitButton7.setFont(new java.awt.Font("Agency FB", 0, 28)); // NOI18N
        SubmitButton7.setForeground(new java.awt.Color(255, 255, 255));
        SubmitButton7.setText("Order");
        SubmitButton7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SubmitButton7.setContentAreaFilled(false);
        SubmitButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitButton7MouseClicked(evt);
            }
        });
        SubmitButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(SubmitButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 170, -1));

        SubmitButton12.setBackground(new java.awt.Color(0, 51, 51));
        SubmitButton12.setFont(new java.awt.Font("Agency FB", 0, 28)); // NOI18N
        SubmitButton12.setForeground(new java.awt.Color(255, 255, 255));
        SubmitButton12.setText("Payment");
        SubmitButton12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SubmitButton12.setContentAreaFilled(false);
        SubmitButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitButton12MouseClicked(evt);
            }
        });
        SubmitButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButton12ActionPerformed(evt);
            }
        });
        jPanel4.add(SubmitButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 170, -1));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 68, 300, -1));

        SubmitButton13.setBackground(new java.awt.Color(0, 51, 51));
        SubmitButton13.setFont(new java.awt.Font("Agency FB", 1, 28)); // NOI18N
        SubmitButton13.setForeground(new java.awt.Color(255, 255, 255));
        SubmitButton13.setText("Buy");
        SubmitButton13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SubmitButton13.setContentAreaFilled(false);
        SubmitButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitButton13MouseClicked(evt);
            }
        });
        SubmitButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButton13ActionPerformed(evt);
            }
        });
        jPanel4.add(SubmitButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 170, -1));

        SubmitButton14.setBackground(new java.awt.Color(0, 51, 51));
        SubmitButton14.setFont(new java.awt.Font("Agency FB", 0, 28)); // NOI18N
        SubmitButton14.setForeground(new java.awt.Color(255, 255, 255));
        SubmitButton14.setText("Sell");
        SubmitButton14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SubmitButton14.setContentAreaFilled(false);
        SubmitButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitButton14MouseClicked(evt);
            }
        });
        SubmitButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButton14ActionPerformed(evt);
            }
        });
        jPanel4.add(SubmitButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 170, -1));

        jScrollPane2.setViewportView(jPanel4);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Buy  Tabel");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, 110, 40));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setText("Name");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 87, 32));

        jComboBox1.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 51, 51));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "option 1", "option 2", "option 3", "option 4", " " }));
        jComboBox1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 90, 22));

        SubmitButton1.setBackground(new java.awt.Color(255, 255, 255));
        SubmitButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SubmitButton1.setForeground(new java.awt.Color(255, 255, 255));
        SubmitButton1.setText("Update");
        SubmitButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SubmitButton1.setContentAreaFilled(false);
        SubmitButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitButton1MouseClicked(evt);
            }
        });
        SubmitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(SubmitButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, -1));

        SubmitButton2.setBackground(new java.awt.Color(255, 255, 255));
        SubmitButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SubmitButton2.setForeground(new java.awt.Color(255, 255, 255));
        SubmitButton2.setText("Add");
        SubmitButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SubmitButton2.setContentAreaFilled(false);
        SubmitButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitButton2MouseClicked(evt);
            }
        });
        SubmitButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(SubmitButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        SubmitButton3.setBackground(new java.awt.Color(255, 255, 255));
        SubmitButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SubmitButton3.setForeground(new java.awt.Color(255, 255, 255));
        SubmitButton3.setText("Delete");
        SubmitButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SubmitButton3.setContentAreaFilled(false);
        SubmitButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitButton3MouseClicked(evt);
            }
        });
        SubmitButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(SubmitButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        jTextField2.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(102, 102, 102));
        jTextField2.setText("jTextField1");
        jTextField2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 215, 28));

        jTextField3.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(102, 102, 102));
        jTextField3.setText("Search");
        jTextField3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 215, 28));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img39one.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 290, 420));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Group 8 (1).png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CHSdb.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1790, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DataBaseBG.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1060));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1101, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        jPanel4.hide();
        jScrollPane2.hide();
        jPanel3.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void SubmitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitButtonMouseClicked
        new signIn().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SubmitButtonMouseClicked

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void SubmitButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitButton5MouseClicked
        try {
            // TODO add your handling code here:
            new employeeCustomer().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(employeeBuy.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_SubmitButton5MouseClicked

    private void SubmitButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitButton5ActionPerformed

    private void SubmitButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitButton7MouseClicked
        // TODO add your handling code here:
        new employeeOrder().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SubmitButton7MouseClicked

    private void SubmitButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitButton7ActionPerformed

    private void SubmitButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitButton12MouseClicked
        // TODO add your handling code here:
        new employeePayment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SubmitButton12MouseClicked

    private void SubmitButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitButton12ActionPerformed

    private void SubmitButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitButton13MouseClicked
        // TODO add your handling code here:
        new employeeBuy().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SubmitButton13MouseClicked

    private void SubmitButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitButton13ActionPerformed

    private void SubmitButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitButton14MouseClicked
        // TODO add your handling code here:
        new employeeSell().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SubmitButton14MouseClicked

    private void SubmitButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitButton14ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void SubmitButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitButton1MouseClicked

    private void SubmitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButton1ActionPerformed

    }//GEN-LAST:event_SubmitButton1ActionPerformed

    private void SubmitButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitButton2MouseClicked

    private void SubmitButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitButton2ActionPerformed

    private void SubmitButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitButton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitButton3MouseClicked

    private void SubmitButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitButton3ActionPerformed

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        jPanel3.hide();
        jPanel4.setVisible(true);
        jScrollPane2.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        jPanel4.hide();
        jScrollPane2.hide();
        jPanel3.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employeeBuy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employeeBuy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employeeBuy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employeeBuy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employeeBuy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogoutSymbol;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JButton SubmitButton1;
    private javax.swing.JButton SubmitButton12;
    private javax.swing.JButton SubmitButton13;
    private javax.swing.JButton SubmitButton14;
    private javax.swing.JButton SubmitButton2;
    private javax.swing.JButton SubmitButton3;
    private javax.swing.JButton SubmitButton5;
    private javax.swing.JButton SubmitButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
