
package computerhardwarestore;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Statement;
import java.sql.*;
import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.text.SimpleDateFormat;  
import java.util.Date;  
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fahee
 */
public class employeeOrder extends javax.swing.JFrame {
    /**
     * Creates new form employeeOrder
     */
    public employeeOrder() {
        initComponents();
        jPanel3.hide();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        LogoutSymbol = new javax.swing.JLabel();
        SubmitButton = new javax.swing.JButton();
        SubmitButton5 = new javax.swing.JButton();
        SubmitButton7 = new javax.swing.JButton();
        SubmitButton12 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        SubmitButton13 = new javax.swing.JButton();
        SubmitButton14 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Show = new javax.swing.JButton();
        Search = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        customername = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProductTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Group 8 (1).png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DashBoard");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 300, 10));

        LogoutSymbol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        jPanel4.add(LogoutSymbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 30, 40));

        SubmitButton.setBackground(new java.awt.Color(0, 51, 51));
        SubmitButton.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        SubmitButton.setForeground(new java.awt.Color(255, 255, 255));
        SubmitButton.setText("Log-Out");
        SubmitButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SubmitButton.setContentAreaFilled(false);
        SubmitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitButtonMouseClicked(evt);
            }
        });
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });
        jPanel4.add(SubmitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, 110, 40));

        SubmitButton5.setBackground(new java.awt.Color(0, 51, 51));
        SubmitButton5.setFont(new java.awt.Font("Agency FB", 0, 28)); // NOI18N
        SubmitButton5.setForeground(new java.awt.Color(255, 255, 255));
        SubmitButton5.setText("Customer");
        SubmitButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SubmitButton5.setContentAreaFilled(false);
        SubmitButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitButton5MouseClicked(evt);
            }
        });
        SubmitButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(SubmitButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 170, -1));

        SubmitButton7.setBackground(new java.awt.Color(0, 51, 51));
        SubmitButton7.setFont(new java.awt.Font("Agency FB", 1, 28)); // NOI18N
        SubmitButton7.setForeground(new java.awt.Color(255, 255, 255));
        SubmitButton7.setText("Order");
        SubmitButton7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SubmitButton7.setContentAreaFilled(false);
        SubmitButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitButton7MouseClicked(evt);
            }
        });
        SubmitButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(SubmitButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 170, -1));

        SubmitButton12.setBackground(new java.awt.Color(0, 51, 51));
        SubmitButton12.setFont(new java.awt.Font("Agency FB", 0, 28)); // NOI18N
        SubmitButton12.setForeground(new java.awt.Color(255, 255, 255));
        SubmitButton12.setText("Payment");
        SubmitButton12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SubmitButton12.setContentAreaFilled(false);
        SubmitButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitButton12MouseClicked(evt);
            }
        });
        SubmitButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButton12ActionPerformed(evt);
            }
        });
        jPanel4.add(SubmitButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 170, -1));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 68, 300, -1));

        SubmitButton13.setBackground(new java.awt.Color(0, 51, 51));
        SubmitButton13.setFont(new java.awt.Font("Agency FB", 0, 28)); // NOI18N
        SubmitButton13.setForeground(new java.awt.Color(255, 255, 255));
        SubmitButton13.setText("Buy");
        SubmitButton13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SubmitButton13.setContentAreaFilled(false);
        SubmitButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitButton13MouseClicked(evt);
            }
        });
        SubmitButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButton13ActionPerformed(evt);
            }
        });
        jPanel4.add(SubmitButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 170, -1));

        SubmitButton14.setBackground(new java.awt.Color(0, 51, 51));
        SubmitButton14.setFont(new java.awt.Font("Agency FB", 0, 28)); // NOI18N
        SubmitButton14.setForeground(new java.awt.Color(255, 255, 255));
        SubmitButton14.setText("Sell");
        SubmitButton14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SubmitButton14.setContentAreaFilled(false);
        SubmitButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitButton14MouseClicked(evt);
            }
        });
        SubmitButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButton14ActionPerformed(evt);
            }
        });
        jPanel4.add(SubmitButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 170, -1));

        jScrollPane2.setViewportView(jPanel4);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Group 8 (1).png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CHSdb.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1790, -1));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Show.setBackground(new java.awt.Color(255, 255, 255));
        Show.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Show.setForeground(new java.awt.Color(255, 255, 255));
        Show.setText("Show");
        Show.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Show.setContentAreaFilled(false);
        Show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowMouseClicked(evt);
            }
        });
        Show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowActionPerformed(evt);
            }
        });
        jPanel3.add(Show, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        Search.setBackground(new java.awt.Color(255, 255, 255));
        Search.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Search.setForeground(new java.awt.Color(255, 255, 255));
        Search.setText("Search");
        Search.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Search.setContentAreaFilled(false);
        Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchMouseClicked(evt);
            }
        });
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        jPanel3.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        jLabel4.setText("Customer ID");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));
        jPanel3.add(customername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 170, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 250, 110));

        ProductTable.setBackground(new java.awt.Color(204, 255, 102));
        ProductTable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ProductTable.setFont(new java.awt.Font("Agency FB", 0, 11)); // NOI18N
        ProductTable.setForeground(new java.awt.Color(102, 102, 0));
        ProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Product", "Amount", "Payment", "Order Date", "Role"
            }
        ));
        ProductTable.setGridColor(new java.awt.Color(0, 102, 102));
        ProductTable.setRowHeight(24);
        ProductTable.setSelectionBackground(new java.awt.Color(0, 102, 102));
        ProductTable.setShowGrid(true);
        ProductTable.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                ProductTableInputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ProductTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 1090, 200));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DataBaseBG.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1060));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1101, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        jPanel4.hide();
        jScrollPane2.hide();
        jPanel3.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void SubmitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitButtonMouseClicked
        new signIn().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SubmitButtonMouseClicked

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void SubmitButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitButton5MouseClicked
        try {
            // TODO add your handling code here:
            new employeeCustomer().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(employeeOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_SubmitButton5MouseClicked

    private void SubmitButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitButton5ActionPerformed

    private void SubmitButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitButton7MouseClicked
        // TODO add your handling code here:
        new employeeOrder().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SubmitButton7MouseClicked

    private void SubmitButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitButton7ActionPerformed

    private void SubmitButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitButton12MouseClicked
        // TODO add your handling code here:
        new employeePayment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SubmitButton12MouseClicked

    private void SubmitButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitButton12ActionPerformed

    private void SubmitButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitButton13MouseClicked
        // TODO add your handling code here:
        new employeeBuy().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SubmitButton13MouseClicked

    private void SubmitButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitButton13ActionPerformed

    private void SubmitButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitButton14MouseClicked
        // TODO add your handling code here:
        new employeeSell().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SubmitButton14MouseClicked

    private void SubmitButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitButton14ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        jPanel3.hide();
        jPanel4.setVisible(true);
        jScrollPane2.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        jPanel4.hide();
        jScrollPane2.hide();
        jPanel3.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void ShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ShowMouseClicked

    private void ShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowActionPerformed
        try {
            jPanel3.setVisible(false);
            Connection mycon = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "hr", "hr");
            Statement stmt = mycon.createStatement();
            ProductTable.setFont(new Font("Serif", Font.BOLD, 15));
            DefaultTableModel model = (DefaultTableModel) ProductTable.getModel();

            model.setRowCount(0);
            
            ResultSet result22 = stmt.executeQuery("select customer_id,customer_name,product.product_name,orders.total_price, payment.payment_type,orders.date_of_order from customer join buys on buys.customer_customer_id = customer.customer_id join product on buys.product_product_id = product.product_id join order_items on order_items.product_product_id = product.product_id join orders on orders.order_id = order_items.order_order_id join payment on payment.order_order_id = orders.order_id");
            while (result22.next()) {
                model.addRow(new Object[]{result22.getInt(1),result22.getString(2),result22.getString(3),result22.getString(4),result22.getString(5),result22.getString(6),"Buy"});
            }
            
            ResultSet sellresult = stmt.executeQuery("select customer_id,customer_name,product.product_name,orders.total_price, payment.payment_type,orders.date_of_order from customer join sells on sells.customer_customer_id = customer.customer_id join product on sells.product_product_id = product.product_id join order_items on order_items.product_product_id = product.product_id join orders on orders.order_id = order_items.order_order_id join payment on payment.order_order_id = orders.order_id");
            while (sellresult.next()) {
                model.addRow(new Object[]{sellresult.getInt(1),sellresult.getString(2),sellresult.getString(3),sellresult.getString(4),sellresult.getString(5),sellresult.getString(6),"Sell"});
            }

        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_ShowActionPerformed

    private void SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseClicked

    }//GEN-LAST:event_SearchMouseClicked

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        try {
            ProductTable.setVisible(true);
            jPanel3.setVisible(false);
            String name = "";

                Connection mycon = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "hr", "hr");
                Statement stmt = mycon.createStatement();
                ProductTable.setFont(new Font("Serif", Font.BOLD, 15));
                DefaultTableModel model = (DefaultTableModel) ProductTable.getModel();
                model.setRowCount(0);
                ResultSet result= stmt.executeQuery("select * from order_details");
                int count = 0;
                
                while (result.next()) {
                    if(customername.getText().equals(result.getString(1))){
                        model.addRow(new Object[]{result.getInt(1),result.getString(2),result.getString(3),result.getString(4),result.getString(5),result.getString(6),"Sell"});
                        count++;
                    }
                }
                
                ResultSet result2= stmt.executeQuery("select * from buy_order_details");
                while (result2.next()) {
                    if(customername.getText().equals(result2.getString(1))){
                        model.addRow(new Object[]{result2.getInt(1),result2.getString(2),result2.getString(3),result2.getString(4),result2.getString(5),result2.getString(6),"Buy"});
                        count++;
                    }
                }
                if(count==0){
                    JOptionPane.showMessageDialog(null,"No Record Found for "+name);
                }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_SearchActionPerformed

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseClicked

    private void ProductTableInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_ProductTableInputMethodTextChanged

    }//GEN-LAST:event_ProductTableInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employeeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employeeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employeeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employeeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employeeOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogoutSymbol;
    private javax.swing.JTable ProductTable;
    private javax.swing.JButton Search;
    private javax.swing.JButton Show;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JButton SubmitButton12;
    private javax.swing.JButton SubmitButton13;
    private javax.swing.JButton SubmitButton14;
    private javax.swing.JButton SubmitButton5;
    private javax.swing.JButton SubmitButton7;
    private javax.swing.JTextField customername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
