
package computerhardwarestore;

import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.sql.*;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class managerEmployee extends javax.swing.JFrame {

    /**
     * Creates new form managerEmployee
     */
    public managerEmployee() {
        initComponents();
        jPanel3.hide();
        Delete1.setVisible(false);
        Update1.setVisible(false);
        employeeCounter.setVisible(false);
        HighestSalaryCounter.setVisible(false);
        LowestSalaryCounter.setVisible(false);
    }
    String Shop = "";
    String oldNaming = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        LogoutSymbol = new javax.swing.JLabel();
        SubmitButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        Products = new javax.swing.JButton();
        Employee = new javax.swing.JButton();
        shop = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Show = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        username = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        rank = new javax.swing.JTextField();
        Salary = new javax.swing.JTextField();
        Update22 = new javax.swing.JButton();
        Search = new javax.swing.JButton();
        tips = new javax.swing.JButton();
        JSalary = new javax.swing.JLabel();
        JShop = new javax.swing.JLabel();
        JName = new javax.swing.JLabel();
        JUsername = new javax.swing.JLabel();
        JRank = new javax.swing.JLabel();
        Delete1 = new javax.swing.JButton();
        Update1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        EmployeeTable = new javax.swing.JTable();
        HighestSalaryCounter = new javax.swing.JPanel();
        JHighestSalary = new javax.swing.JLabel();
        HighestSalary = new javax.swing.JLabel();
        employeeCounter = new javax.swing.JPanel();
        JTotalEmployees = new javax.swing.JLabel();
        employeeNo = new javax.swing.JLabel();
        LowestSalaryCounter = new javax.swing.JPanel();
        JLowestSalary = new javax.swing.JLabel();
        LowestSalary = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Group 8 (1).png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DashBoard");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 300, 10));

        LogoutSymbol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        jPanel4.add(LogoutSymbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 30, 40));

        SubmitButton.setBackground(new java.awt.Color(0, 51, 51));
        SubmitButton.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        SubmitButton.setForeground(new java.awt.Color(255, 255, 255));
        SubmitButton.setText("Log-Out");
        SubmitButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SubmitButton.setContentAreaFilled(false);
        SubmitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitButtonMouseClicked(evt);
            }
        });
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });
        jPanel4.add(SubmitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, 110, 40));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 68, 300, -1));

        Products.setBackground(new java.awt.Color(0, 51, 51));
        Products.setFont(new java.awt.Font("Agency FB", 0, 28)); // NOI18N
        Products.setForeground(new java.awt.Color(255, 255, 255));
        Products.setText("Products");
        Products.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Products.setContentAreaFilled(false);
        Products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductsMouseClicked(evt);
            }
        });
        Products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductsActionPerformed(evt);
            }
        });
        jPanel4.add(Products, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 170, -1));

        Employee.setBackground(new java.awt.Color(0, 51, 51));
        Employee.setFont(new java.awt.Font("Agency FB", 1, 28)); // NOI18N
        Employee.setForeground(new java.awt.Color(255, 255, 255));
        Employee.setText("Employee");
        Employee.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Employee.setContentAreaFilled(false);
        Employee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeeMouseClicked(evt);
            }
        });
        Employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeActionPerformed(evt);
            }
        });
        jPanel4.add(Employee, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 170, -1));

        shop.setBackground(new java.awt.Color(0, 51, 51));
        shop.setFont(new java.awt.Font("Agency FB", 0, 28)); // NOI18N
        shop.setForeground(new java.awt.Color(255, 255, 255));
        shop.setText("Shop");
        shop.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        shop.setContentAreaFilled(false);
        shop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shopMouseClicked(evt);
            }
        });
        shop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shopActionPerformed(evt);
            }
        });
        jPanel4.add(shop, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 170, -1));

        jScrollPane2.setViewportView(jPanel4);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Group 8 (1).png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CHSdb.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1790, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Employee  Tabel");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 180, 40));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Show.setBackground(new java.awt.Color(255, 255, 255));
        Show.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Show.setForeground(new java.awt.Color(255, 255, 255));
        Show.setText("Show");
        Show.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Show.setContentAreaFilled(false);
        Show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowMouseClicked(evt);
            }
        });
        Show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowActionPerformed(evt);
            }
        });
        jPanel3.add(Show, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        Add.setBackground(new java.awt.Color(255, 255, 255));
        Add.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Add.setForeground(new java.awt.Color(255, 255, 255));
        Add.setText("Add");
        Add.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Add.setContentAreaFilled(false);
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMouseClicked(evt);
            }
        });
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        jPanel3.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        Delete.setBackground(new java.awt.Color(255, 255, 255));
        Delete.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Delete.setForeground(new java.awt.Color(255, 255, 255));
        Delete.setText("Delete");
        Delete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Delete.setContentAreaFilled(false);
        Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteMouseClicked(evt);
            }
        });
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel3.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        username.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        username.setForeground(new java.awt.Color(102, 102, 102));
        username.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 170, 28));

        Name.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        Name.setForeground(new java.awt.Color(102, 102, 102));
        Name.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        jPanel3.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 170, 28));

        rank.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        rank.setForeground(new java.awt.Color(102, 102, 102));
        rank.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(rank, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 170, 30));

        Salary.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        Salary.setForeground(new java.awt.Color(102, 102, 102));
        Salary.setText("0");
        Salary.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalaryActionPerformed(evt);
            }
        });
        jPanel3.add(Salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 180, 30));

        Update22.setBackground(new java.awt.Color(255, 255, 255));
        Update22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Update22.setForeground(new java.awt.Color(255, 255, 255));
        Update22.setText("Update");
        Update22.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Update22.setContentAreaFilled(false);
        Update22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Update22MouseClicked(evt);
            }
        });
        Update22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update22ActionPerformed(evt);
            }
        });
        jPanel3.add(Update22, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        Search.setBackground(new java.awt.Color(255, 255, 255));
        Search.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Search.setForeground(new java.awt.Color(255, 255, 255));
        Search.setText("Search");
        Search.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Search.setContentAreaFilled(false);
        Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchMouseClicked(evt);
            }
        });
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        jPanel3.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        tips.setBackground(new java.awt.Color(204, 0, 0));
        tips.setText("Tips");
        tips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipsActionPerformed(evt);
            }
        });
        jPanel3.add(tips, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, -1));

        JSalary.setText("Salary");
        jPanel3.add(JSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        JShop.setText("Shop Branch");
        jPanel3.add(JShop, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        JName.setText("Name");
        jPanel3.add(JName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        JUsername.setText("User Name");
        jPanel3.add(JUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        JRank.setText("Rank");
        jPanel3.add(JRank, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        Delete1.setBackground(new java.awt.Color(153, 0, 0));
        Delete1.setText("Remove");
        Delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete1ActionPerformed(evt);
            }
        });
        jPanel3.add(Delete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        Update1.setBackground(new java.awt.Color(0, 51, 51));
        Update1.setText("Update");
        Update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update1ActionPerformed(evt);
            }
        });
        jPanel3.add(Update1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(0, 51, 51));
        jComboBox1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rawalpindi", "Multan", "Karachi" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 180, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 410, 220));

        EmployeeTable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        EmployeeTable.setFont(new java.awt.Font("Agency FB", 0, 11)); // NOI18N
        EmployeeTable.setForeground(new java.awt.Color(51, 51, 51));
        EmployeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "User Name", "Rank", "Salary", "Shop"
            }
        ));
        EmployeeTable.setGridColor(new java.awt.Color(0, 102, 102));
        EmployeeTable.setRowHeight(24);
        EmployeeTable.setSelectionBackground(new java.awt.Color(0, 102, 102));
        EmployeeTable.setShowGrid(true);
        EmployeeTable.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                EmployeeTableInputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(EmployeeTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 680, 190));

        HighestSalaryCounter.setBackground(new java.awt.Color(0, 51, 51));

        JHighestSalary.setText("Highest Salary");

        HighestSalary.setText("jLabel3");

        javax.swing.GroupLayout HighestSalaryCounterLayout = new javax.swing.GroupLayout(HighestSalaryCounter);
        HighestSalaryCounter.setLayout(HighestSalaryCounterLayout);
        HighestSalaryCounterLayout.setHorizontalGroup(
            HighestSalaryCounterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HighestSalaryCounterLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(JHighestSalary)
                .addGap(16, 16, 16))
            .addGroup(HighestSalaryCounterLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(HighestSalary)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HighestSalaryCounterLayout.setVerticalGroup(
            HighestSalaryCounterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HighestSalaryCounterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JHighestSalary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HighestSalary)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(HighestSalaryCounter, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 520, -1, 60));

        employeeCounter.setBackground(new java.awt.Color(0, 51, 51));

        JTotalEmployees.setText("Total Employees");

        employeeNo.setText("jLabel4");

        javax.swing.GroupLayout employeeCounterLayout = new javax.swing.GroupLayout(employeeCounter);
        employeeCounter.setLayout(employeeCounterLayout);
        employeeCounterLayout.setHorizontalGroup(
            employeeCounterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeCounterLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(JTotalEmployees)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeeCounterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(employeeNo)
                .addGap(40, 40, 40))
        );
        employeeCounterLayout.setVerticalGroup(
            employeeCounterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeCounterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JTotalEmployees)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employeeNo)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel1.add(employeeCounter, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 520, -1, 70));

        LowestSalaryCounter.setBackground(new java.awt.Color(0, 51, 51));

        JLowestSalary.setText("Lowest Salary");

        LowestSalary.setText("jLabel7");

        javax.swing.GroupLayout LowestSalaryCounterLayout = new javax.swing.GroupLayout(LowestSalaryCounter);
        LowestSalaryCounter.setLayout(LowestSalaryCounterLayout);
        LowestSalaryCounterLayout.setHorizontalGroup(
            LowestSalaryCounterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LowestSalaryCounterLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(JLowestSalary)
                .addContainerGap(27, Short.MAX_VALUE))
            .addComponent(LowestSalary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LowestSalaryCounterLayout.setVerticalGroup(
            LowestSalaryCounterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LowestSalaryCounterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLowestSalary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LowestSalary)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(LowestSalaryCounter, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 520, 120, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DataBaseBG.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1060));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1101, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        jPanel4.hide();
        jScrollPane2.hide();
        jPanel3.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void SubmitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitButtonMouseClicked
        new signIn().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SubmitButtonMouseClicked

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        jPanel3.hide();
        jPanel4.setVisible(true);
        jScrollPane2.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        jPanel4.hide();
        jScrollPane2.hide();
        jPanel3.setVisible(true);

    }//GEN-LAST:event_jLabel1MouseClicked

    private void ProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductsMouseClicked
        // TODO add your handling code here:
        new managerProduct().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ProductsMouseClicked

    private void ProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductsActionPerformed

    private void EmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeMouseClicked
        // TODO add your handling code here:
        new managerEmployee().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EmployeeMouseClicked

    private void EmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeActionPerformed

    private void shopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shopMouseClicked
        // TODO add your handling code here:
        new managerShop().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_shopMouseClicked

    private void shopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shopActionPerformed

    private void ShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ShowMouseClicked

    private void ShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowActionPerformed
        try {
            Connection mycon = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "hr", "hr");
            Statement stmt = mycon.createStatement();
            EmployeeTable.setFont(new Font("Serif", Font.BOLD, 15));
            DefaultTableModel model = (DefaultTableModel) EmployeeTable.getModel();
            BufferedReader br = new BufferedReader(new FileReader(new File("D:\\branch.txt")));
            String st = "";
            String test = "";
            while ((st = br.readLine()) != null){
                test = st;
                System.out.println(st);
            }
            ResultSet result = stmt.executeQuery("select * from employee_details where shop_branch = '"+test+"'");

            model.setRowCount(0);
            while (result.next()) {
                System.out.println(result.getString(1)+"   "+result.getString(2)+"   "+result.getString(3)+"   "+result.getString(4)+"   "+result.getInt(5)+"   "+result.getString(5));
                model.addRow(new Object[]{result.getString(1),result.getString(2),result.getString(3),result.getString(4),result.getInt(5),result.getString(6)});
            }
            ResultSet result2 = stmt.executeQuery("select count(*) from employee_details where shop_branch = '"+test+"'");
            employeeCounter.setVisible(true);
            JTotalEmployees.setFont(new Font("Serif", Font.BOLD, 15));
            employeeNo.setFont(new Font("Serif", Font.BOLD, 20));
            JTotalEmployees.setForeground(Color.white);
            employeeNo.setForeground(Color.white);
            employeeNo. setHorizontalAlignment(JLabel. CENTER);
            while(result2.next()){
                String count = result2.getString(1);
                employeeNo.setText(count);
            }
            ResultSet result3 = stmt.executeQuery("select employee_name, employee_salary from employees where employee_salary in (select max(employee_salary) from employee_details where shop_branch = '"+test+"')");
            HighestSalaryCounter.setVisible(true);
            System.out.println("yaha ara ha");
            JHighestSalary.setFont(new Font("Serif", Font.BOLD, 15));
            HighestSalary.setFont(new Font("Serif", Font.BOLD, 20));
            JHighestSalary.setForeground(Color.white);
            HighestSalary.setForeground(Color.white);
            HighestSalary. setHorizontalAlignment(JLabel. CENTER);
            while(result3.next()){
                String name="";
                String salary = "";
                name = result3.getString(1);
                salary = result3.getString(2);
                HighestSalary.setText(name+" : "+salary);
            }

            ResultSet result4 = stmt.executeQuery("select employee_name, employee_salary from employees where employee_salary in (select min(employee_salary) from employee_details  where shop_branch = '"+test+"')");
            LowestSalaryCounter.setVisible(true);
            JLowestSalary.setFont(new Font("Serif", Font.BOLD, 15));
            LowestSalary.setFont(new Font("Serif", Font.BOLD, 20));
            JLowestSalary.setForeground(Color.white);
            LowestSalary.setForeground(Color.white);
            LowestSalary. setHorizontalAlignment(JLabel. CENTER);
            while(result4.next()){
                String name="";
                String salary = "";
                name = result4.getString(1);
                salary = result4.getString(2);
                LowestSalary.setText(name+" : "+salary);
            }

        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_ShowActionPerformed

    private void AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseClicked
        try {
            String name = "";
            String user_name  = "";
            String user_password = "";
            int salary = 0;
            String shop = "";
            name = Name.getText();
            user_password = rank.getText();

            System.out.println("This is the password"+user_password);
            user_name = username.getText();
            salary = Integer.parseInt(Salary.getText());
            shop = Shop;
            name = Name.getText();
            if(name.equals("") || (user_name.equals("")) || (user_password.equals("")) || (salary==0) || (shop.equals(""))){
                JOptionPane.showMessageDialog(null, "Enter All Fields to Add Data");
            }
            else{
                int shopId = 1;
                int shopCheck = 1;
                int user_salary = 100;
                int employeeId = 1;
                Connection mycon = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "hr", "hr");
                Statement stmt = mycon.createStatement();
                Statement stmt1 = mycon.createStatement();
                Statement stmt2 = mycon.createStatement();
                ResultSet employeeCount = stmt.executeQuery("select employee_id from employees");
                while (employeeCount.next()) {
                    if(employeeId==employeeCount.getInt(1)){
                        employeeId++;
                        System.out.println("employee Id:"+employeeId);
                    }
                    else{

                        break;
                    }
                }
                int same1 = 0;
                ResultSet shopCount = stmt1.executeQuery("select * from shop");
                ResultSet shopCount2 = stmt.executeQuery("select shop_id from shop");
                while (shopCount.next()) {
                    System.out.println(shopCount.getInt(1)+" "+shopCount.getString(2));

                    if(shop.equalsIgnoreCase(shopCount.getString(2))){

                        shopCheck = shopCount.getInt(1);
                        same1++;
                        break;
                    }

                }
                int shopnewId=1;
                if(same1==0){
                    JOptionPane.showMessageDialog(null, "No Branch Found");
                }

                int user_newSalary = 200;

                if(same1!=0){
                    stmt.executeUpdate("Insert into employees values('"+employeeId+"', '" + name + "', '" + user_name + "', '" + salary + "', '" + shopCheck + "', '" + user_password + "')");
                }

            }

        } catch (Exception e) {
            System.out.println(e.toString());
        }
        Name.setText("");
        rank.setText("");
        username.setText("");
        Salary.setText("0");

    }//GEN-LAST:event_AddMouseClicked

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddActionPerformed

    private void DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteMouseClicked

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed

        username.setVisible(false);
        rank.setVisible(false);
        Salary.setVisible(false);
        jComboBox1.setVisible(false);
        Delete1.setVisible(true);
        Delete.setEnabled(false);

        JUsername.setVisible(false);
        JRank.setVisible(false);
        JSalary.setVisible(false);
        JShop.setVisible(false);
        JName.setText("Employee ID");
    }//GEN-LAST:event_DeleteActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void SalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalaryActionPerformed

    private void Update22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Update22MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Update22MouseClicked

    private void Update22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update22ActionPerformed
        try{
            int id = 0;
            id = Integer.parseInt(Name.getText());
            Connection mycon = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "hr", "hr");
            Statement stmt = mycon.createStatement();
            EmployeeTable.setFont(new Font("Serif", Font.BOLD, 15));
            DefaultTableModel model = (DefaultTableModel) EmployeeTable.getModel();
            model.setRowCount(0);
            ResultSet result = stmt.executeQuery("select employee_id, employee_name, employee_username, employee_password, employee_salary, shop.shop_branch from employees join shop on shop.shop_id = employees.shop_shop_id where employees.employee_id="+id+"");
            int count = 0;
            oldNaming = Name.getText();
            while (result.next()) {
                JOptionPane.showMessageDialog(null,"Record Found for "+id);
                Name.setText(result.getString(2));
                username.setText(result.getString(3));
                rank.setText(result.getString(4));
                Salary.setText(result.getString(5));
                jComboBox1.setSelectedItem(result.getString(6));

                count++;
            }
            if(count==0){
                JOptionPane.showMessageDialog(null,"No Record Found for "+id);
            }
            else{
                JName.setText("New Name");
                JRank.setText("New Password");
                JUsername.setText("New User Name");
                JSalary.setText("New Salary");
                JShop.setText("New Branch");
                Update1.setVisible(true);
                Update22.setEnabled(false);

            }

        }
        catch (Exception e) {
            System.out.println(e.toString());
        }

    }//GEN-LAST:event_Update22ActionPerformed

    private void SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseClicked
        try {
            String name = "";
            name = Name.getText();

            if(((!Name.getText().equals("") && username.getText().equals("") && rank.getText().equals("") && Salary.getText().equals("0")))
                || ((Name.getText().equals("") && !username.getText().equals("") && rank.getText().equals("") && Salary.getText().equals("0")))
                || ((Name.getText().equals("") && username.getText().equals("") && !rank.getText().equals("") && Salary.getText().equals("0")))
                || ((Name.getText().equals("") && username.getText().equals("") && rank.getText().equals("") && !Salary.getText().equals("0")))
                || ((Name.getText().equals("") && username.getText().equals("") && rank.getText().equals("") && Salary.getText().equals("0")))){

                Connection mycon = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "hr", "hr");
                Statement stmt = mycon.createStatement();
                EmployeeTable.setFont(new Font("Serif", Font.BOLD, 15));
                DefaultTableModel model = (DefaultTableModel) EmployeeTable.getModel();
                model.setRowCount(0);
                ResultSet result=null;
                if(!Name.getText().equals("")){
                    result = stmt.executeQuery("select employee_id, employee_name, employee_username, employee_password, employee_salary, shop.shop_branch from employees join shop on shop.shop_id = employees.shop_shop_id");
                }
                else if(!username.getText().equals("")){
                    result = stmt.executeQuery("select employee_id, employee_name, employee_username, employee_password, employee_salary, shop.shop_branch from employees join shop on shop.shop_id = employees.shop_shop_id");
                }
                else if(!rank.getText().equals("")){
                    result = stmt.executeQuery("select employee_id, employee_name, employee_username, employee_password, employee_salary, shop.shop_branch from employees join shop on shop.shop_id = employees.shop_shop_id where employees.employee_password='"+rank.getText()+"'");
                }
                else if(!Salary.getText().equals("0")){
                    result = stmt.executeQuery("select employee_id, employee_name, employee_username, employee_password, employee_salary, shop.shop_branch from employees join shop on shop.shop_id = employees.shop_shop_id where employee_salary="+Integer.parseInt(Salary.getText())+"");
                }
                else{
                    result = stmt.executeQuery("select employee_id, employee_name, employee_username, employee_password, employee_salary, shop.shop_branch from employees join shop on shop.shop_id = employees.shop_shop_id where shop.shop_branch='"+jComboBox1.getSelectedItem()+"'");
                }

                int count = 0;
                while (result.next()) {
                    System.out.println(result.getString(1)+"   "+result.getString(2)+"   "+result.getString(3)+"   "+result.getString(4)+"   "+result.getInt(5)+" "+result.getString(6));

                    if(Name.getText().equals("")){
                        count++;
                        model.addRow(new Object[]{result.getString(1),result.getString(2),result.getString(3),result.getString(4),result.getInt(5),result.getString(6)});
                    }
                    else{
                        if(name.equalsIgnoreCase(result.getString(2))){
                            model.addRow(new Object[]{result.getString(1),result.getString(2),result.getString(3),result.getString(4),result.getInt(5),result.getString(6)});
                            count++;
                        }
                    }
                }
                if(count==0){
                    JOptionPane.showMessageDialog(null,"No Record Found for "+name);
                }
                else if(count!=0 && (!Name.getText().equals("") || !username.getText().equals("") || !rank.getText().equals("") || !Salary.getText().equals("0"))){
                    JOptionPane.showMessageDialog(null,"Record Found for "+name);
                }
                Name.setText("");
                rank.setText("");
                username.setText("");
                Salary.setText("0");

            }
            else{
                JOptionPane.showMessageDialog(null, "Enter Only 1 Field To Search");
                Name.setText("");
                rank.setText("");
                username.setText("");
                Salary.setText("0");

            }

        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_SearchMouseClicked

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchActionPerformed

    private void tipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipsActionPerformed
        JOptionPane.showMessageDialog(null,"Enter Employee ID In Name Field To Update");
    }//GEN-LAST:event_tipsActionPerformed

    private void Delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete1ActionPerformed
        try{
            int count = 0;
            int id;
            try{
                id = Integer.parseInt(Name.getText());
                Connection mycon = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "hr", "hr");
                Statement stmt = mycon.createStatement();

                ResultSet result = stmt.executeQuery("select * from employees where employee_id = '"+id+"' ");
                int fetchedID=0;
                while (result.next()) {
                    fetchedID = result.getInt(1);
                }
                stmt.executeUpdate("Delete from employees where employee_id = '"+id+"'");
                if(fetchedID==0){
                    JOptionPane.showMessageDialog(null,"No Record Found for: "+id);
                }
                else if(fetchedID!=0){
                    JOptionPane.showMessageDialog(null,"Record Deleted for: "+id);
                }
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Not A Valid ID");
            }

        } catch (Exception e) {
            System.out.println(e.toString());
        }
        Name.setText("");
        username.setVisible(true);
        rank.setVisible(true);
        Salary.setVisible(true);
        jComboBox1.setVisible(true);
        Delete1.setVisible(false);
        Delete.setEnabled(true);

        JUsername.setVisible(true);
        JRank.setVisible(true);
        JSalary.setVisible(true);
        JShop.setVisible(true);
        JName.setText("Name");
    }//GEN-LAST:event_Delete1ActionPerformed

    private void Update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update1ActionPerformed
        try{

            String name = "";
            String user_name = "";
            String user_password = "";
            int salary = 0;

            name = Name.getText();
            user_password = rank.getText();
            user_name = username.getText();
            salary = Integer.parseInt(Salary.getText());

            Connection mycon = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "hr", "hr");
            Statement stmt = mycon.createStatement();
            EmployeeTable.setFont(new Font("Serif", Font.BOLD, 15));

            DefaultTableModel model = (DefaultTableModel) EmployeeTable.getModel();
            model.setRowCount(0);
            int id = Integer.parseInt(oldNaming);
            ResultSet result = stmt.executeQuery("select employee_id, employee_name, employee_username, employee_password, employee_salary, shop.shop_branch from employees join shop on shop.shop_id = employees.shop_shop_id where employees.employee_id="+id+"");
            int count = 0;
            String oldName="";
            String oldName2="";
            String old = "";
            String oldPassword = "";
            String oldShop  = "";
            int oldSalary = 0;
            int shopId = 1;
            int shopCheck = 1;
            int salaryId = 1;
            int employeeId = 1;
            while (result.next()) {
                oldName = result.getString(2);
                oldName2 = result.getString(2);//to use in salary and shop query
                old = result.getString(3);
                oldPassword = result.getString(4);
                oldSalary = result.getInt(5);
                oldShop = result.getString(6);

                System.out.println(result.getString(2)+" "+ result.getString(3)+" "+ result.getString(4)+" "+ result.getInt(5)+" "+ result.getString(6));
                count++;
            }
            stmt.executeUpdate("update employees set employee_name = '"+name+"' where employee_id="+oldNaming+"");
            stmt.executeUpdate("update employees set employee_username = '"+user_name+"' where employee_id="+oldNaming+"");
            stmt.executeUpdate("update employees set employee_password = '"+user_password+"' where employee_id="+oldNaming+"");
            stmt.executeUpdate("update employees set employee_salary = '"+salary+"' where employee_id="+oldNaming+"");
            //            stmt.executeUpdate("update employees set salary_salary_id = '"+salary+"' where salary_salary_id="+oldSalary+"");
            //            stmt.executeUpdate("update employees set shop_shop_id = '"+shop+"' where shop_shop_id='karachi'");

            //            int oldSalaryId = 0;
            //            int newSalaryId = 0;
            //            boolean newSalaryCheck=false;
            //            ResultSet resultSalary = stmt.executeQuery("select salary_id, salary.salary from salary");
            //            while(resultSalary.next()){
                //                if(oldSalary==resultSalary.getInt(2)){
                    //
                    //                    oldSalaryId = resultSalary.getInt(1);
                    //
                    //                }
                //                if(salary==resultSalary.getInt(2)){
                    //
                    //
                    //                    newSalaryCheck=true;
                    //                    newSalaryId = resultSalary.getInt(1);
                    //
                    //                }
                //            }
            //            if(newSalaryCheck==true){
                //                stmt.executeUpdate("update employees set salary_salary_id = "+newSalaryId+" where employee_id="+oldNaming+"");
                //
                //            }
            //            else{
                //                ResultSet salaryCount = stmt.executeQuery("select salary_id from salary");
                //                    int salaryId2=1;
                //                    while(salaryCount.next()){
                    //
                    //                        if(salaryId2==salaryCount.getInt(1)){
                        //
                        //                            salaryId2++;
                        //                        }
                    //                        else{
                        //                            break;
                        //                        }
                    //                    }
                //                    stmt.executeUpdate("Insert into salary values("+salaryId2+", '" + salary + "', 1)");
                //                    stmt.executeUpdate("update employees set salary_salary_id = "+salaryId2+" where employee_id="+oldNaming+"");
                //            }

            int oldShopId = 0;
            int newShopId = 0;
            boolean newShopCheck=false;
            ResultSet resultShop = stmt.executeQuery("select shop_id, shop_branch from shop");
            while(resultShop.next()){
                if(oldShop.equalsIgnoreCase(resultShop.getString(2))){

                    oldShopId = resultShop.getInt(1);

                }
                if(Shop.equalsIgnoreCase(resultShop.getString(2))){

                    newShopCheck=true;
                    newShopId = resultShop.getInt(1);

                }

            }
            int noBranch=0;
            if(newShopCheck==true){

                stmt.executeUpdate("update employees set shop_shop_id = "+newShopId+" where employee_id="+oldNaming+"");
            }
            else{
                JOptionPane.showMessageDialog(null, "No Branch Available With This Name");
                noBranch=1;
            }

            //            stmt.executeUpdate("update salary set salary.salary = '"+salary+"' where salary.salary='"+oldSalary+"'");
            //            stmt.executeUpdate("update shop set shop_branch = '"+shop+"' where shop_branch='"+oldShop+"'");
            if(noBranch==0){
                JOptionPane.showMessageDialog(null,"Data Updated Successfully ");
            }

        } catch (Exception e) {
            System.out.println(e.toString());
        }
        JName.setText("Name");
        JRank.setText("User Name");
        JUsername.setText("Password");
        JSalary.setText("Salary");
        JShop.setText("Branch");

        Name.setText("");
        rank.setText("");
        username.setText("");
        Salary.setText("0");
        Update1.setVisible(false);
        Update22.setEnabled(true);
    }//GEN-LAST:event_Update1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        Shop = jComboBox1.getSelectedItem().toString();

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseClicked

    private void EmployeeTableInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_EmployeeTableInputMethodTextChanged

    }//GEN-LAST:event_EmployeeTableInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(managerEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(managerEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(managerEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(managerEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new managerEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Delete1;
    private javax.swing.JButton Employee;
    private javax.swing.JTable EmployeeTable;
    private javax.swing.JLabel HighestSalary;
    private javax.swing.JPanel HighestSalaryCounter;
    private javax.swing.JLabel JHighestSalary;
    private javax.swing.JLabel JLowestSalary;
    private javax.swing.JLabel JName;
    private javax.swing.JLabel JRank;
    private javax.swing.JLabel JSalary;
    private javax.swing.JLabel JShop;
    private javax.swing.JLabel JTotalEmployees;
    private javax.swing.JLabel JUsername;
    private javax.swing.JLabel LogoutSymbol;
    private javax.swing.JLabel LowestSalary;
    private javax.swing.JPanel LowestSalaryCounter;
    private javax.swing.JTextField Name;
    private javax.swing.JButton Products;
    private javax.swing.JTextField Salary;
    private javax.swing.JButton Search;
    private javax.swing.JButton Show;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JButton Update1;
    private javax.swing.JButton Update22;
    private javax.swing.JPanel employeeCounter;
    private javax.swing.JLabel employeeNo;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField rank;
    private javax.swing.JButton shop;
    private javax.swing.JButton tips;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
